# Generated by Django 2.2.5 on 2019-10-28 08:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currenttransaction',
            name='borrowed',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='currenttransaction',
            name='desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='currenttransaction',
            name='lent',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='newnotification',
            name='desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='oldnotification',
            name='desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='Desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='borrowed',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='transactionhistory',
            name='lent',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='name',
            field=models.CharField(default='Your Name', max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='phone_number',
            field=models.CharField(blank=True, max_length=500, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', message='Invalid Number')]),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='user_address',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
