# Generated by Django 2.2.5 on 2019-10-26 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_newnotification_oldnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newnotification',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
